### ISSUE TITLE
请教为什么报错，cannot reshape tensor of 0 elements into shape [-1, 0] 

### ISSUE THREAD

**Issue by mahu168** [Plachtaa/seed-vc#37]
命令：
python inference.py --source /root/autodl-tmp/test/test_vocals.wav --target /root/autodl-tmp/test/dingzhen_0.wav --output /root/autodl-tmp/test/ --diffusion-steps 50 --length-adjust 1.0 --inference-cfg-rate 0.7 --f0-condition True --auto-f0-adjust False --semi-tone-shift 0

报错：
Warning: Skipped loading some keys due to shape mismatch: {'estimator.input_pos'}
cfm loaded
length_regulator loaded
Loading weights from nvidia/bigvgan_v2_44khz_128band_512x
Removing weight norm...
Traceback (most recent call last):
  File "/root/autodl-tmp/seed-vc/inference.py", line 278, in <module>
    main(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/seed-vc/inference.py", line 144, in main
    ref_waves_16k = torchaudio.functional.resample(ref_audio, sr, 16000)
  File "/root/miniconda3/lib/python3.10/site-packages/torchaudio/functional/functional.py", line 1530, in resample
    resampled = _apply_sinc_resample_kernel(waveform, orig_freq, new_freq, gcd, kernel, width)
  File "/root/miniconda3/lib/python3.10/site-packages/torchaudio/functional/functional.py", line 1462, in _apply_sinc_resample_kernel
    waveform = waveform.view(-1, shape[-1])
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

补充：
--source 换官方的歌曲没问题，用自己的就不行

**Comment by CoreBedtime** [comment]
same

**Comment by Plachtaa** [comment]
可能是双声道的问题，你的source可以发一下吗

**Comment by mahu168** [comment]
> 可能是双声道的问题，你的source可以发一下吗

可以的
[test_vocals.zip](https://github.com/user-attachments/files/17567006/test_vocals.zip)

**Comment by Plachtaa** [comment]
看了一下是因为source超过了30秒导致的，目前建议长音频先用app.py推理，之后会把分段处理的逻辑同步到inference.py

**Comment by mytait** [comment]
in inference.py in line 252:
` ref_audio = ref_audio[:(sr * 30 - source_audio.size(-1))]`

the audio for reference speaker is cut to to 30 seconds MINUS the length of the source audio. So if the source audio is longer than 30 seconds the code crashes in line 256:

`ref_waves_16k = torchaudio.functional.resample(ref_audio, sr, 16000)`

`->cannot reshape tensor of **0 elements** into shape [-1, 0]`

because the audio is empty.


Is this on purpose?

Even if i remove the subtraction to be:
`` ref_audio = ref_audio[:(sr * 30 )]``

like in line 249, later the output is only 30 seconds ignoring the remaining audio.

If the audio is cut to 30 seconds anyway, why let it crash? or why cut it?

This is not documented in the README. it would be good for the code to work in chunks like in app.py

**Comment by Plachtaa** [comment]
现在inference.py可以按照app.py一样的逻辑推理任意长度的音频了

**Comment by mytait** [comment]
wow thanks!! :dancers:  :smiley:
